title: Alejandro Armas
logo: "/images/logo.jpg?raw=true"
description: > 
  Economist and data scientist working in interesting way to work around data. <br><br>
  Passionate about data visualization, web scraping, and machine learning.
  <br><br>
  <br><br>
  <a href="https://www.linkedin.com/in/alejandroarmasbr/">View My LinkedIn Profile</a> 
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: UA-000000-0 
